---
deployment:
  tasks:
    - cd $HOME && curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y > $HOME/rust_install.log 2>&1
    - source $HOME/.cargo/env
    - cargo --version > $HOME/cargo_version.txt 2>&1
