---
deployment:
  tasks:
    - echo "debug" > rust_setup.log
    - cd $HOME
    - pwd >> rust_setup.log
    - whoami >> rust_setup.log
    - id >> rust_setup.log
    - apt --version >> rust_setup.log 2>&1
    - cat /etc/os-release >> rust_setup.log 2>&1
